2024-06-02 14:26:25,225 INFO    MainThread:167028 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-06-02 14:26:25,226 INFO    MainThread:167028 [wandb_setup.py:_flush():76] Configure stats pid to 167028
2024-06-02 14:26:25,226 INFO    MainThread:167028 [wandb_setup.py:_flush():76] Loading settings from /home/lukas_ronald/.config/wandb/settings
2024-06-02 14:26:25,226 INFO    MainThread:167028 [wandb_setup.py:_flush():76] Loading settings from /home/lukas_ronald/adl4cv/notebooks/wandb/settings
2024-06-02 14:26:25,226 INFO    MainThread:167028 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-06-02 14:26:25,226 INFO    MainThread:167028 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-06-02 14:26:25,226 INFO    MainThread:167028 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-06-02 14:26:25,226 INFO    MainThread:167028 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-06-02 14:26:25,226 INFO    MainThread:167028 [wandb_init.py:_log_setup():520] Logging user logs to ../wandb/run-20240602_142625-rb3mnvpe/logs/debug.log
2024-06-02 14:26:25,226 INFO    MainThread:167028 [wandb_init.py:_log_setup():521] Logging internal logs to ../wandb/run-20240602_142625-rb3mnvpe/logs/debug-internal.log
2024-06-02 14:26:25,226 INFO    MainThread:167028 [wandb_init.py:init():560] calling init triggers
2024-06-02 14:26:25,226 INFO    MainThread:167028 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.001, 'architecture': 'PointNet', 'dataset': 'ModelNet10', 'epochs': 1}
2024-06-02 14:26:25,226 INFO    MainThread:167028 [wandb_init.py:init():585] re-initializing run, found existing run on stack: g2jomc18
2024-06-02 14:26:25,227 INFO    MainThread:167028 [wandb_run.py:_finish():2103] finishing run adl4cv24/Pointnet/g2jomc18
2024-06-02 14:26:25,227 INFO    MainThread:167028 [jupyter.py:save_history():445] not saving jupyter history
2024-06-02 14:26:25,227 INFO    MainThread:167028 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-06-02 14:26:25,227 INFO    MainThread:167028 [wandb_init.py:_jupyter_teardown():448] cleaning up jupyter logic
2024-06-02 14:26:25,227 INFO    MainThread:167028 [wandb_run.py:_atexit_cleanup():2343] got exitcode: 0
2024-06-02 14:26:25,227 INFO    MainThread:167028 [wandb_run.py:_restore():2326] restore
2024-06-02 14:26:25,227 INFO    MainThread:167028 [wandb_run.py:_restore():2332] restore done
2024-06-02 14:26:46,890 INFO    MainThread:167028 [wandb_init.py:init():610] starting backend
2024-06-02 14:26:46,890 INFO    MainThread:167028 [wandb_init.py:init():614] setting up manager
2024-06-02 14:26:46,893 INFO    MainThread:167028 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-06-02 14:26:46,893 INFO    MainThread:167028 [wandb_init.py:init():622] backend started and connected
2024-06-02 14:26:46,898 INFO    MainThread:167028 [wandb_run.py:_label_probe_notebook():1328] probe notebook
2024-06-02 14:26:46,898 INFO    MainThread:167028 [wandb_run.py:_label_probe_notebook():1338] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-06-02 14:26:46,898 INFO    MainThread:167028 [wandb_init.py:init():711] updated telemetry
2024-06-02 14:26:46,900 INFO    MainThread:167028 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
